<?php

/**
 * Implements hook_views_api().
 */
function guq_admin_views_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_views_default_views().
 */
function guq_admin_views_views_default_views() {
  $module = 'guq_admin_views';
  $directory = 'views';
  $extension = 'view.inc';
  $name = 'view';

  $views = array();
  // Find all the files in the directory with the correct extension.
  $files = file_scan_directory(drupal_get_path('module', $module) . "/$directory", "/.$extension/");
  foreach ($files as $path => $file) {
    require $path;
    if (isset($$name)) {
      $views[$$name->name] = $$name;
    }
  }

  return $views;
}
